apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  namespace: url-shortener
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: shortener
  HTTP_PORT: "8080"
  SHUTDOWN_TIMEOUT: 10s
  LOG_LEVEL: info
